//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPR_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEPREntities : DbContext
    {
        public DBEPREntities()
            : base("name=DBEPREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LOG> LOGS { get; set; }
        public virtual DbSet<MACHINE> MACHINES { get; set; }
        public virtual DbSet<MACHINETYPE> MACHINETYPES { get; set; }
        public virtual DbSet<MANUFACTURER> MANUFACTURERS { get; set; }
        public virtual DbSet<OEM> OEMS { get; set; }
        public virtual DbSet<ORDER> ORDERS { get; set; }
        public virtual DbSet<PART> PARTS { get; set; }
        public virtual DbSet<PERMISSION> PERMISSIONS { get; set; }
        public virtual DbSet<ROLE> ROLES { get; set; }
        public virtual DbSet<SUPPLIER> SUPPLIERS { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<USERSIMAGE> USERSIMAGES { get; set; }
        public virtual DbSet<UZAUTOSUPPLIER> UZAUTOSUPPLIERS { get; set; }
        public virtual DbSet<Warehouse> WAREHOUSES { get; set; }
        public virtual DbSet<WH_INS> WH_INS { get; set; }
        public virtual DbSet<WH_OUTS> WH_OUTS { get; set; }
    }
}
