//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPR_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MACHINE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MACHINE()
        {
            this.PARTS = new HashSet<PART>();
        }
    
        public string Name { get; set; }
        public string Description { get; set; }
        public int UzAutoSupplierID { get; set; }
        public int ManufacturerID { get; set; }
        public string Lifespan { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> InstalledDate { get; set; }
        public int TypeID { get; set; }
        public int ID { get; set; }
        public string PartNumber { get; set; }
    
        public virtual MACHINETYPE MACHINETYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PART> PARTS { get; set; }
        public virtual MANUFACTURER MANUFACTURER { get; set; }
        public virtual UZAUTOSUPPLIER UZAUTOSUPPLIER { get; set; }
    }
}
