//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPR_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        public int ID { get; set; }
        public string OrderNumber { get; set; }
        public int UserID { get; set; }
        public int PartID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public double Qty { get; set; }
        public byte[] TechnicalTask { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Specification { get; set; }
        public double CurrentPartPrice { get; set; }
        public string Currency { get; set; }
        public string Status { get; set; }
        public int UzAutoSupplierID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual UZAUTOSUPPLIER UZAUTOSUPPLIER { get; set; }
        public virtual PART PART { get; set; }
        public virtual USER USER { get; set; }
    }
}
