//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPR_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PART
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string PartNumber { get; set; }
        public byte[] Photo { get; set; }
        public int UzAutoSupplierID { get; set; }
        public string NamePlate { get; set; }
        public int ManufacturerID { get; set; }
        public int SupplierID { get; set; }
        public int OEMID { get; set; }
        public int MachineID { get; set; }
        public string OEMPartNumber { get; set; }
    
        public virtual MACHINE MACHINE { get; set; }
        public virtual MANUFACTURER MANUFACTURER { get; set; }
        public virtual OEM OEM { get; set; }
        public virtual SUPPLIER SUPPLIER { get; set; }
        public virtual UZAUTOSUPPLIER UZAUTOSUPPLIER { get; set; }
    }
}
